# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='petitionthershold',
            new_name='petitionthreshold',
        ),
    ]
