# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0002_auto_20171215_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='petitionurl',
            field=models.CharField(default='http://localhost:8000', max_length=150),
        ),
    ]
